import { BusinessType, Language, OrderStatus } from "@lls/core"

type StatusTexts = Partial<Record<OrderStatus, string>>

/** Bot message texts. Keep Uzbek (Latin) and Russian in sync. */
const BASE = {
    [Language.UZ]: {
        currency: "so'm",
        newOrder: "🆕 Yangi buyurtma",
        order: "Buyurtma",
        delivery: "Yetkazib berish",
        deposit: "Idish garovi",
        free: "bepul",
        total: "Jami",
        landmark: "mo'ljal",
        map: "Xaritada ochish",
        status: "Holat",
        courier: "Kuryer",
        bottlesBack: "Bo'sh idish qaytaradi: {n} ta",
        cancelledByCustomer: "❌ Mijoz buyurtmani bekor qildi",
        cancel: "❌ Bekor qilish",
        reason: "Sabab",
        kg: "kg",
        statusNames: {
            [OrderStatus.PENDING]: "🆕 Yangi",
            [OrderStatus.ACCEPTED]: "✅ Qabul qilindi",
            [OrderStatus.PREPARING]: "📦 Yig'ilmoqda",
            [OrderStatus.READY]: "📦 Tayyor",
            [OrderStatus.PICKED_UP]: "🚚 Yo'lda",
            [OrderStatus.DELIVERED]: "🏁 Yetkazildi",
            [OrderStatus.CANCELLED]: "❌ Bekor qilindi",
        } as Record<OrderStatus, string>,
        actions: {
            [OrderStatus.ACCEPTED]: "✅ Qabul qilish",
            [OrderStatus.PREPARING]: "📦 Yig'ishni boshlash",
            [OrderStatus.READY]: "📦 Tayyor",
            [OrderStatus.PICKED_UP]: "🚚 Jo'natish",
            [OrderStatus.DELIVERED]: "🏁 Yetkazildi",
        } as StatusTexts,
        customerStatus: {
            [OrderStatus.ACCEPTED]: "✅ #{n} buyurtmangiz qabul qilindi.",
            [OrderStatus.PREPARING]: "📦 #{n} buyurtmangiz yig'ilmoqda.",
            [OrderStatus.READY]: "📦 #{n} buyurtmangiz tayyor.",
            [OrderStatus.PICKED_UP]: "🚚 #{n} buyurtmangiz yo'lda. Tez orada yetib boradi!",
            [OrderStatus.DELIVERED]: "🏁 #{n} buyurtmangiz yetkazildi. Rahmat!",
            [OrderStatus.CANCELLED]: "❌ #{n} buyurtmangiz bekor qilindi.",
        } as StatusTexts,
        courierOnTheWay: "🚚 #{n} buyurtmangizni {courier} olib kelmoqda.",
        shopWelcome:
            "Assalomu alaykum! {shop} katalogini oching va bir necha bosishda buyurtma bering.",
        openMenu: "🛒 Katalogni ochish",
        phoneSaved: "✅ Telefon raqamingiz saqlandi.",
        platformWelcome:
            "LLS — tumaningiz do'konlari bir joyda. Mahsulotni qidiring va do'kondan buyurtma bering.\n\nDo'kon egasimisiz? O'z buyurtma botingizni ulang.",
        connectShop: "🏪 Do'konni ulash",
        openShowcase: "🔍 Do'konlar va mahsulotlar",
        showcaseOrder: "🛍 LLS vitrinasidan · komissiya {rate}%: {sum}",
        showcaseJoined:
            "🛍 {shop} LLS vitrinasiga qo'shildi. Mijozlar uni LLS botida topadi.\nKomissiya: vitrina orqali sotilgan tovarlarning {rate}%. O'z botingiz orqali sotuvdan komissiya olinmaydi.",
        showcaseLeft: "{shop} LLS vitrinasidan olindi.",
        showcaseUsage:
            "Buyruq: /market <slug> <foiz>, masalan /market osh-markaz 5\nO'chirish: /market <slug> off",
        showcaseSet: "✅ {shop}: vitrinada, komissiya {rate}%",
        showcaseOff: "✅ {shop}: vitrinadan olindi",
        botNotConnected:
            "⚠️ {shop} tasdiqlandi, lekin bot ulanmadi: {reason}\nQayta urinish: /reconnect {slug}",
        botConnected: "✅ {shop}: bot ulandi.",
        reconnectUsage: "Buyruq: /reconnect <slug>, masalan /reconnect osh-markaz",
        shopNotActive: "{shop} hali tasdiqlanmagan.",
        alertServerError: "🚨 LLS serverida xato",
        alertNotificationFailed: "🚨 LLS: xabar yuborilmadi",
        alertQuiet: "Shu turdagi keyingi ogohlantirish {minutes} daqiqadan keyin.",
        applicationReceived: "✅ {shop} arizasi qabul qilindi. Tekshiruvdan so'ng xabar beramiz.",
        shopApproved: "🎉 {shop} ishga tushdi! Mijozlaringizga ushbu havolani yuboring:",
        shopRejected: "😔 {shop} arizasi rad etildi. Savollar bo'lsa, bizga yozing.",
        newShop: "🏪 Yangi do'kon",
        shopTypes: {
            [BusinessType.FOOD]: "ovqat",
            [BusinessType.WATER]: "suv",
            [BusinessType.GROCERY]: "oziq-ovqat",
        } as Record<BusinessType, string>,
        ownerLabel: "Egasi",
        approve: "✅ Tasdiqlash",
        reject: "❌ Rad etish",
        shopStatus: {
            active: "✅ Tasdiqlandi",
            disabled: "❌ Rad etildi",
            pending: "⏳ Kutilmoqda",
        },
        callbackDone: "Tayyor",
        callbackOutdated: "Holat allaqachon o'zgargan",
        callbackForbidden: "Bu amal siz uchun emas",
        courierBotWelcome:
            "👋 Bu LLS kuryer boti: do'konlar buyurtmalari shu yerga keladi. Ishni boshlash uchun do'kon egasidan taklif havolasini so'rang.",
        courierBotHome:
            "🚚 Siz kuryersiz: {shops}. Smenaga chiqing — buyurtmalar shu yerga keladi.",
        courierPending:
            "⏳ {shop} egasi sizni tasdiqlashini kuting. Tasdiqlansa, shu yerga yozamiz.",
        courierAskPhone: "📱 Do'kon siz bilan bog'lana olishi uchun telefon raqamingizni yuboring.",
        sharePhone: "📱 Raqamni yuborish",
        courierJoinedOwner: "🚚 {name} kuryer bo'lish taklifini qabul qildi. Tasdiqlaysizmi?",
        approveCourier: "✅ Tasdiqlash",
        declineCourier: "❌ Rad etish",
        courierApprovedOwner: "✅ {name} endi sizning kuryeringiz.",
        courierDeclinedOwner: "❌ {name} rad etildi.",
        courierApproved:
            "✅ {shop} sizni kuryer sifatida tasdiqladi. Smenaga chiqing — buyurtmalar shu yerga keladi.",
        courierDeclined: "😔 {shop} sizni kuryer sifatida tasdiqlamadi.",
        courierRemovedFromShop: "↩️ {shop} sizni kuryerlar ro'yxatidan chiqardi.",
        inviteInvalid: "😔 Bu taklif havolasi ishlamaydi. Do'kon egasidan yangisini so'rang.",
        myDeliveries: "🚚 Yetkazishlarim",
        courierCard: "🚚 Yetkazib berish",
        collect: "💵 Mijozdan olish: {sum}",
        bottlesToCollect: "🔁 Bo'sh idish olish: {n} ta",
        courierActions: {
            [OrderStatus.PICKED_UP]: "🚚 Oldim",
            [OrderStatus.DELIVERED]: "🏁 Yetkazdim",
        } as StatusTexts,
        courierWait: "⏳ Buyurtma tayyor bo'lganda xabar beramiz.",
        courierReady: "📦 {shop}: #{n} buyurtma tayyor — olib keting.",
        paidCash: "🏁 💵 Naqd pul",
        paidCard: "🏁 💳 Kartaga o'tkazma",
        paidLater: "🏁 🕓 Keyinroq to'laydi",
        payment: {
            cashDue: "💵 To'lov: naqd pul",
            transferAwaited: "💳 Kartaga o'tkazma · kutilmoqda",
            paidCash: "✅ Naqd pul bilan to'langan",
            paidCard: "✅ O'tkazma bilan to'langan",
            debt: "🕓 To'lanmagan (qarz)",
            refundDue: "↩️ Mijozga qaytarish kerak",
            refunded: "↩️ Qaytarildi",
        },
        withCourier: "kuryerda: {name}",
        nothingToCollect: "✅ To'langan — mijozdan pul olmang",
        collectTransfer: "💳 Mijoz kartaga o'tkazadi — naqd olmang",
        paymentReceived: "✅ #{n} buyurtma uchun to'lov qabul qilindi. Rahmat!",
        reportCaption: "📊 {shop}: buyurtmalar, {from} — {to}",
        csv: {
            headers: [
                "Raqam",
                "Sana",
                "Holat",
                "Mijoz",
                "Telefon",
                "Manzil",
                "Tovarlar",
                "Yetkazish",
                "Garov",
                "Jami",
                "To'lov usuli",
                "To'lov holati",
                "To'langan vaqt",
                "Kuryer",
                "Kanal",
                "LLS komissiyasi",
            ],
            method: { cash: "naqd", card_transfer: "o'tkazma" },
            payment: {
                unpaid: "to'lanmagan",
                awaiting: "kutilmoqda",
                paid: "to'langan",
                refund_due: "qaytarish kerak",
                refunded: "qaytarildi",
            },
            channel: { shop_bot: "do'kon boti", marketplace: "LLS vitrinasi" },
        },
        posterCaption: "🖨 {shop} uchun QR-kod. Chop eting yoki Instagramga joylang.",
        courierRemoved: "↩️ {shop}: #{n} buyurtma boshqa kuryerga berildi.",
    },
    [Language.RU]: {
        currency: "сум",
        newOrder: "🆕 Новый заказ",
        order: "Заказ",
        delivery: "Доставка",
        deposit: "Залог за бутыли",
        free: "бесплатно",
        total: "Итого",
        landmark: "ориентир",
        map: "Открыть на карте",
        status: "Статус",
        courier: "Доставщик",
        bottlesBack: "Вернёт пустых бутылей: {n}",
        cancelledByCustomer: "❌ Клиент отменил заказ",
        cancel: "❌ Отменить",
        reason: "Причина",
        kg: "кг",
        statusNames: {
            [OrderStatus.PENDING]: "🆕 Новый",
            [OrderStatus.ACCEPTED]: "✅ Принят",
            [OrderStatus.PREPARING]: "📦 Собираем",
            [OrderStatus.READY]: "📦 Готов",
            [OrderStatus.PICKED_UP]: "🚚 В пути",
            [OrderStatus.DELIVERED]: "🏁 Доставлен",
            [OrderStatus.CANCELLED]: "❌ Отменён",
        } as Record<OrderStatus, string>,
        actions: {
            [OrderStatus.ACCEPTED]: "✅ Принять",
            [OrderStatus.PREPARING]: "📦 Собрать",
            [OrderStatus.READY]: "📦 Готово",
            [OrderStatus.PICKED_UP]: "🚚 Отправить",
            [OrderStatus.DELIVERED]: "🏁 Доставлен",
        } as StatusTexts,
        customerStatus: {
            [OrderStatus.ACCEPTED]: "✅ Заказ #{n} принят.",
            [OrderStatus.PREPARING]: "📦 Собираем заказ #{n}.",
            [OrderStatus.READY]: "📦 Заказ #{n} готов.",
            [OrderStatus.PICKED_UP]: "🚚 Заказ #{n} в пути. Скоро будет у вас!",
            [OrderStatus.DELIVERED]: "🏁 Заказ #{n} доставлен. Спасибо!",
            [OrderStatus.CANCELLED]: "❌ Заказ #{n} отменён.",
        } as StatusTexts,
        courierOnTheWay: "🚚 Заказ #{n} везёт {courier}.",
        shopWelcome: "Здравствуйте! Откройте каталог {shop} и закажите в пару нажатий.",
        openMenu: "🛒 Открыть каталог",
        phoneSaved: "✅ Ваш номер сохранён.",
        platformWelcome:
            "LLS — магазины вашего района в одном месте. Найдите товар и закажите в магазине.\n\nВы владелец магазина? Подключите свой бот для заказов.",
        connectShop: "🏪 Подключить магазин",
        openShowcase: "🔍 Магазины и товары",
        showcaseOrder: "🛍 Из витрины LLS · комиссия {rate}%: {sum}",
        showcaseJoined:
            "🛍 {shop} теперь в витрине LLS. Клиенты найдут вас в боте LLS.\nКомиссия: {rate}% от товаров, проданных через витрину. С продаж через ваш бот комиссии нет.",
        showcaseLeft: "{shop} убран из витрины LLS.",
        showcaseUsage:
            "Команда: /market <slug> <процент>, например /market osh-markaz 5\nУбрать: /market <slug> off",
        showcaseSet: "✅ {shop}: в витрине, комиссия {rate}%",
        showcaseOff: "✅ {shop}: убран из витрины",
        botNotConnected:
            "⚠️ {shop} одобрен, но бот не подключился: {reason}\nПовторить: /reconnect {slug}",
        botConnected: "✅ {shop}: бот подключён.",
        reconnectUsage: "Команда: /reconnect <slug>, например /reconnect osh-markaz",
        shopNotActive: "{shop} ещё не одобрен.",
        alertServerError: "🚨 Ошибка на сервере LLS",
        alertNotificationFailed: "🚨 LLS: сообщение не отправлено",
        alertQuiet: "Следующее оповещение этого вида не раньше чем через {minutes} мин.",
        applicationReceived: "✅ Заявка {shop} принята. Сообщим после проверки.",
        shopApproved: "🎉 {shop} запущен! Отправьте клиентам эту ссылку:",
        shopRejected: "😔 Заявка {shop} отклонена. Если есть вопросы, напишите нам.",
        newShop: "🏪 Новый магазин",
        shopTypes: {
            [BusinessType.FOOD]: "еда",
            [BusinessType.WATER]: "вода",
            [BusinessType.GROCERY]: "продукты",
        } as Record<BusinessType, string>,
        ownerLabel: "Владелец",
        approve: "✅ Одобрить",
        reject: "❌ Отклонить",
        shopStatus: { active: "✅ Одобрен", disabled: "❌ Отклонён", pending: "⏳ Ждёт проверки" },
        callbackDone: "Готово",
        callbackOutdated: "Статус уже изменился",
        callbackForbidden: "Это действие не для вас",
        courierBotWelcome:
            "👋 Это бот доставщиков LLS: сюда приходят заказы магазинов. Чтобы начать, попросите у владельца магазина ссылку-приглашение.",
        courierBotHome: "🚚 Вы доставщик: {shops}. Выйдите на смену — заказы будут приходить сюда.",
        courierPending: "⏳ Ждём, пока владелец {shop} вас подтвердит. Напишем сюда.",
        courierAskPhone: "📱 Отправьте номер телефона, чтобы магазин мог вам позвонить.",
        sharePhone: "📱 Отправить номер",
        courierJoinedOwner: "🚚 {name} принял приглашение стать доставщиком. Подтвердить?",
        approveCourier: "✅ Подтвердить",
        declineCourier: "❌ Отклонить",
        courierApprovedOwner: "✅ {name} теперь ваш доставщик.",
        courierDeclinedOwner: "❌ {name}: отклонён.",
        courierApproved:
            "✅ {shop} подтвердил вас как доставщика. Выйдите на смену — заказы будут приходить сюда.",
        courierDeclined: "😔 {shop} не подтвердил вас как доставщика.",
        courierRemovedFromShop: "↩️ {shop} убрал вас из своих доставщиков.",
        inviteInvalid: "😔 Эта ссылка-приглашение не работает. Попросите у владельца новую.",
        myDeliveries: "🚚 Мои доставки",
        courierCard: "🚚 Доставка",
        collect: "💵 Взять с клиента: {sum}",
        bottlesToCollect: "🔁 Забрать пустых бутылей: {n}",
        courierActions: {
            [OrderStatus.PICKED_UP]: "🚚 Забрал",
            [OrderStatus.DELIVERED]: "🏁 Доставил",
        } as StatusTexts,
        courierWait: "⏳ Сообщим, когда заказ будет готов.",
        courierReady: "📦 {shop}: заказ #{n} готов — можно забирать.",
        paidCash: "🏁 💵 Наличными",
        paidCard: "🏁 💳 Переводом на карту",
        paidLater: "🏁 🕓 Заплатит позже",
        payment: {
            cashDue: "💵 Оплата: наличными",
            transferAwaited: "💳 Перевод на карту · ждём",
            paidCash: "✅ Оплачено наличными",
            paidCard: "✅ Оплачено переводом",
            debt: "🕓 Не оплачено (долг)",
            refundDue: "↩️ Нужно вернуть клиенту",
            refunded: "↩️ Возвращено",
        },
        withCourier: "у доставщика: {name}",
        nothingToCollect: "✅ Оплачено — денег с клиента не брать",
        collectTransfer: "💳 Клиент платит переводом — наличные не брать",
        paymentReceived: "✅ Оплата заказа #{n} получена. Спасибо!",
        reportCaption: "📊 {shop}: заказы, {from} — {to}",
        csv: {
            headers: [
                "Номер",
                "Дата",
                "Статус",
                "Клиент",
                "Телефон",
                "Адрес",
                "Товары",
                "Доставка",
                "Залог",
                "Итого",
                "Способ оплаты",
                "Оплата",
                "Оплачено",
                "Доставщик",
                "Канал",
                "Комиссия LLS",
            ],
            method: { cash: "наличные", card_transfer: "перевод" },
            payment: {
                unpaid: "не оплачено",
                awaiting: "ждём",
                paid: "оплачено",
                refund_due: "вернуть",
                refunded: "возвращено",
            },
            channel: { shop_bot: "бот магазина", marketplace: "витрина LLS" },
        },
        posterCaption: "🖨 QR-код {shop}. Распечатайте или выложите в Instagram.",
        courierRemoved: "↩️ {shop}: заказ #{n} передан другому доставщику.",
    },
}

export type BotTexts = (typeof BASE)[Language]

/** Food shops cook; water and grocery shops collect goods. Only these words differ. */
const FOOD: Record<Language, Partial<BotTexts>> = {
    [Language.UZ]: {
        statusNames: { ...BASE.uz.statusNames, [OrderStatus.PREPARING]: "👨‍🍳 Tayyorlanmoqda" },
        actions: { ...BASE.uz.actions, [OrderStatus.PREPARING]: "👨‍🍳 Tayyorlashni boshlash" },
        customerStatus: {
            ...BASE.uz.customerStatus,
            [OrderStatus.PREPARING]: "👨‍🍳 #{n} buyurtmangiz tayyorlanmoqda.",
            [OrderStatus.DELIVERED]: "🏁 #{n} buyurtmangiz yetkazildi. Yoqimli ishtaha!",
        },
        shopWelcome:
            "Assalomu alaykum! {shop} menyusini oching va bir necha bosishda buyurtma bering.",
        openMenu: "🍽 Menyuni ochish",
    },
    [Language.RU]: {
        statusNames: { ...BASE.ru.statusNames, [OrderStatus.PREPARING]: "👨‍🍳 Готовится" },
        actions: { ...BASE.ru.actions, [OrderStatus.PREPARING]: "👨‍🍳 Начать готовить" },
        customerStatus: {
            ...BASE.ru.customerStatus,
            [OrderStatus.PREPARING]: "👨‍🍳 Заказ #{n} готовится.",
            [OrderStatus.DELIVERED]: "🏁 Заказ #{n} доставлен. Приятного аппетита!",
        },
        shopWelcome: "Здравствуйте! Откройте меню {shop} и закажите в пару нажатий.",
        openMenu: "🍽 Открыть меню",
    },
}

/** Texts in the reader's language, worded for the shop's kind of business. */
export function textsFor(language: Language, type?: BusinessType): BotTexts {
    return type === BusinessType.FOOD ? { ...BASE[language], ...FOOD[language] } : BASE[language]
}

/** "{shop}" / "#{n}" placeholders. */
export function fill(template: string, values: Record<string, string | number>): string {
    return template.replace(/\{(\w+)\}/g, (match, key: string) =>
        key in values ? String(values[key]) : match,
    )
}
